devGrasys/forms/lecturer.py
# -*- coding: utf-8 -*-
"""
    :author: Jifan Jiang
    :url: https://github.com/fn19980304
"""

from flask_wtf import FlaskForm
from flask_ckeditor import CKEditorField
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import StringField, SubmitField, PasswordField, BooleanField, TextAreaField, ValidationError, HiddenField
from wtforms.validators import DataRequired, Length, Regexp, EqualTo
from wtforms.fields.html5 import DateField

from devGrasys.models import Lecturer, Course


class LoginFormLecturer(FlaskForm):
    user_id = StringField('用户ID', validators=[DataRequired(), Length(10, 10)])
    password = PasswordField('密码', validators=[DataRequired()])
    remember_me = BooleanField('记住我')
    submit = SubmitField('登录')


class RegisterFormLecturer(FlaskForm):
    name = StringField('用户名称', validators=[DataRequired(), Length(1, 30)])
    user_id = StringField('用户ID', validators=[DataRequired(), Length(10, 10), Regexp('^[L][0-9]*$',
                                                                                       message='Lecturer ID should '
                                                                                               'begin with L.')])
    password = PasswordField('密码', validators=[DataRequired(), Length(8, 128), EqualTo('password2')])
    password2 = PasswordField('确认密码', validators=[DataRequired()])
    submit = SubmitField('提交')

    def validate_user_id(self, field):
        if Lecturer.query.filter_by(user_id=field.data).first():
            raise ValidationError('ID已经被其他用户注册！')


class CreateCourseForm(FlaskForm):
    name = StringField('课程名称', validators=[DataRequired(), Length(1, 30)])
    intro = TextAreaField('课程介绍', validators=[DataRequired()])
    submit = SubmitField('创建')

    def validate_class_name(self, field):
        if Course.query.filter_by(name=field.data).first():
            raise ValidationError('课程名已经被其他讲师使用！')


class AdminCourseForm(FlaskForm):
    name = StringField('课程名称', validators=[DataRequired(), Length(1, 30)])
    intro = TextAreaField('课程介绍', validators=[DataRequired()])
    submit = SubmitField('修改')

    def validate_class_name(self, field):
        if Course.query.filter_by(name=field.data).first():
            raise ValidationError('课程名已经被其他讲师使用！')


class AssignHomeworkForm(FlaskForm):
    title = StringField('作业标题', validators=[DataRequired(), Length(1, 30)])
    description = CKEditorField('作业描述', validators=[DataRequired()])
    deadline = DateField('截止日期', format='%Y-%m-%d')
    submit = SubmitField('布置')


class EditProfileFormLecturer(FlaskForm):
    name = StringField('用户名称', validators=[DataRequired(), Length(1, 30)])
    submit = SubmitField('修改')


class UploadAvatarFormLecturer(FlaskForm):
    image = FileField('上传', validators=[
        FileRequired(),
        FileAllowed(['jpg', 'png'], '文件格式应为 .jpg 或 .png.')
    ])
    submit = SubmitField('上传')


class CropAvatarFormLecturer(FlaskForm):
    x = HiddenField()
    y = HiddenField()
    w = HiddenField()
    h = HiddenField()
    submit = SubmitField('裁剪并上传')

devGrasys/blueprints/lecturer.py
# -*- coding: utf-8 -*-
"""
    :author: Jifan Jiang
    :url: https://github.com/fn19980304
"""
from datetime import datetime

from flask import render_template, flash, redirect, url_for, Blueprint, send_from_directory, current_app, request
from flask_login import login_required, login_user, logout_user, current_user

from devGrasys.models import Lecturer, Course, Homework, Student, Answer
from devGrasys.forms.lecturer import RegisterFormLecturer, LoginFormLecturer, CreateCourseForm, AdminCourseForm, \
    AssignHomeworkForm, EditProfileFormLecturer, CropAvatarFormLecturer, UploadAvatarFormLecturer
from devGrasys.utils import redirect_back, flash_errors
from devGrasys.extensions import db, avatars

lecturer_bp = Blueprint('lecturer', __name__)


@lecturer_bp.route('/', methods=['GET'])
def index_lecturer():
    if current_user.is_authenticated:
        user = current_user
        courses = Course.query.filter_by(lecturer=user).all()
        return render_template('lecturer/index_lecturer.html', courses=courses)
    return render_template('lecturer/index_lecturer.html')


@lecturer_bp.route('/login', methods=['GET', 'POST'])
def login_lecturer():
    if current_user.is_authenticated:
        return redirect(url_for('lecturer.index_lecturer'))

    form = LoginFormLecturer()
    if form.validate_on_submit():
        user = Lecturer.query.filter_by(user_id=form.user_id.data).first()
        if user is not None and user.validate_password(form.password.data):
            if login_user(user, form.remember_me.data):
                flash('登录成功。', 'info')
                return redirect_back()
        flash('ID或密码不正确。', 'warning')

    return render_template('lecturer/login_lecturer.html', form=form)


@lecturer_bp.route('/logout')
@login_required
def logout_lecturer():
    logout_user()
    flash('注销成功。', 'info')
    return redirect(url_for('main.index'))


@lecturer_bp.route('/register', methods=['GET', 'POST'])
def register_lecturer():
    if current_user.is_authenticated:
        return redirect(url_for('lecturer.index_lecturer'))

    form = RegisterFormLecturer()
    if form.validate_on_submit():
        name = form.name.data
        user_id = form.user_id.data
        password = form.password.data
        user = Lecturer(user_id=user_id, name=name)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('lecturer.login_lecturer'))
    return render_template('lecturer/register_lecturer.html', form=form)


@lecturer_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@lecturer_bp.route('/create', methods=['GET', 'POST'])
def create_course():
    form = CreateCourseForm()
    lecturer = current_user
    if form.validate_on_submit():
        name = form.name.data
        intro = form.intro.data
        lecturer_name = lecturer.name
        course = Course(name=name, intro=intro, lecturer_name=lecturer_name)
        lecturer.courses.append(course)
        db.session.add(course)
        db.session.commit()
        return redirect(url_for('lecturer.index_lecturer'))
    return render_template('lecturer/create_course.html', form=form)


@lecturer_bp.route('/<course_name>')
def view_course(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    return render_template('lecturer/view_course.html', course=course)


@lecturer_bp.route('/<course_name>/end', methods=['POST'])
def end_course(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    db.session.delete(course)
    db.session.commit()
    flash('课程结束。', 'success')
    return redirect(url_for('lecturer.index_lecturer'))


@lecturer_bp.route('/<course_name>/students')
def show_students(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['USER_PER_PAGE']
    pagination = course.students.paginate(page, per_page)
    students = pagination.items
    return render_template('lecturer/course_students.html', course=course, pagination=pagination, students=students)


@lecturer_bp.route('/<course_name>/assistants')
def show_assistants(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['USER_PER_PAGE']
    pagination = course.assistants.paginate(page, per_page)
    assistants = pagination.items
    return render_template('lecturer/course_assistants.html', course=course, pagination=pagination,
                           assistants=assistants)


@lecturer_bp.route('/<course_name>/admin', methods=['GET', 'POST'])
def edit_course(course_name):
    form = AdminCourseForm()
    course = Course.query.filter_by(name=course_name).first_or_404()
    if form.validate_on_submit():
        course.name = form.name.data
        course.intro = form.intro.data
        db.session.commit()
        flash('上传成功。', 'success')
        return redirect(url_for('lecturer.view_course', course_name=course.name))
    form.name.data = course.name
    form.intro.data = course.intro
    return render_template('lecturer/edit_course.html', form=form)


@lecturer_bp.route('/<course_name>/picture')
def change_picture(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    upload_form = UploadAvatarFormLecturer()
    crop_form = CropAvatarFormLecturer()
    return render_template('lecturer/change_picture.html', course=course, upload_form=upload_form, crop_form=crop_form)


@lecturer_bp.route('/<course_name>/picture/upload', methods=['POST'])
def upload_picture(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    form = UploadAvatarFormLecturer()
    if form.validate_on_submit():
        image = form.image.data
        filename = avatars.save_avatar(image)
        course.avatar_raw = filename
        db.session.commit()
        flash('图片上传成功, 请裁剪。', 'success')
    flash_errors(form)
    return redirect(url_for('lecturer.change_picture', course_name=course.name))


@lecturer_bp.route('/<course_name>/picture/crop', methods=['POST'])
def crop_picture(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    form = CropAvatarFormLecturer()
    if form.validate_on_submit():
        x = form.x.data
        y = form.y.data
        w = form.w.data
        h = form.h.data
        filenames = avatars.crop_avatar(course.avatar_raw, x, y, w, h)
        course.avatar_s = filenames[0]
        course.avatar_m = filenames[1]
        course.avatar_l = filenames[2]
        db.session.commit()
        flash('上传成功。', 'success')
    flash_errors(form)
    return redirect(url_for('lecturer.change_picture', course_name=course.name))


@lecturer_bp.route('/select', methods=['GET'])
def select_course():
    user = current_user
    courses = Course.query.filter_by(lecturer=user).all()
    return render_template('lecturer/select_course.html', courses=courses)


@lecturer_bp.route('/select/<course_name>', methods=['GET', 'POST'])
def view_homework(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    homework_group = Homework.query.filter_by(course=course)
    form = AssignHomeworkForm()
    current_time = datetime.utcnow()
    if form.validate_on_submit():
        title = form.title.data
        description = form.description.data
        deadline = form.deadline.data
        new_homework = Homework(title=title, description=description, deadline=deadline)
        course.homework_group.append(new_homework)
        db.session.add(new_homework)
        db.session.commit()
        return redirect(url_for('lecturer.view_homework', course_name=course.name))
    return render_template('lecturer/view_homework.html', course=course, homework_group=homework_group, form=form,
                           current_time=current_time)


@lecturer_bp.route('/select/<course_name>/<homework_title>', methods=['GET'])
def check_homework(course_name, homework_title):
    course = Course.query.filter_by(name=course_name).first_or_404()
    students = course.students
    homework = Homework.query.filter_by(course=course).filter_by(title=homework_title).first_or_404()
    answers = homework.answers
    submitted_number = 0
    for student in students:
        if student.is_submitted(homework=homework):
            submitted_number += 1
    return render_template('lecturer/check_homework.html', course=course, homework=homework, students=students,
                           answers=answers,
                           submitted_number=submitted_number)


@lecturer_bp.route('/select/<course_name>/<homework_title>/<student_name>', methods=['GET'])
def check_student(course_name, homework_title, student_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    homework = Homework.query.filter_by(course=course).filter_by(title=homework_title).first_or_404()
    student = Student.query.filter_by(name=student_name).first_or_404()
    answer = Answer.query.filter_by(homework=homework).filter_by(student=student).first_or_404()
    return render_template('lecturer/check_student.html', homework=homework, answer=answer, student=student)


@lecturer_bp.route('/settings/profile', methods=['GET', 'POST'])
def edit_profile():
    form = EditProfileFormLecturer()
    if form.validate_on_submit():
        current_user.name = form.name.data
        db.session.commit()
        flash('信息更新。', 'success')
        return redirect(url_for('lecturer.index_lecturer'))
    form.name.data = current_user.name
    return render_template('lecturer/settings/edit_profile.html', form=form)


@lecturer_bp.route('/settings/avatar')
def change_avatar():
    upload_form = UploadAvatarFormLecturer()
    crop_form = CropAvatarFormLecturer()

devGrasys/templates/lecturer/admin_course.html
{% extends 'lecturer/base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/nav.html' import render_nav_item %}

{% block title %}Admin Course{% endblock %}

{% block content %}
    <div class="card w-100 bg-light">
        <h3 class="card-header">Admin Course</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

devGrasys/templates/lecturer/base.html
{% extends 'base.html' %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('lecturer.index_lecturer') }}">
                <img src="{{ url_for('static', filename='favicon_index.ico') }}" alt="devGrasys">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <div class="navbar-nav mr-auto">
                    {% if current_user.is_authenticated %}
                        {{ render_nav_item('lecturer.index_lecturer', '主页') }}
                        {{ render_nav_item('lecturer.create_course', '创建课程') }}
                        {{ render_nav_item('lecturer.select_course', '布置 / 检查') }}
                    {% else %}
                        {{ render_nav_item('lecturer.index_lecturer', '主页') }}
                    {% endif %}
                </div>
            </div>
            <div class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                    <div class="dropdown nav-item">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">
                            <img class="avatar-xs"
                                 src="{{ url_for('lecturer.get_avatar', filename=current_user.avatar_s) }}">
                            <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" role="menu">
                            <h6 class="dropdown-header">以 {{ current_user.name }} 登录</h6>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('lecturer.edit_profile') }}">
                                <span class="oi oi-cog"></span> 个人设置
                            </a>
                            <a class="dropdown-item" href="{{ url_for('lecturer.logout_lecturer') }}">
                                <span class="oi oi-power-standby"></span> 注销
                            </a>
                        </div>
                    </div>
                {% else %}
                {% endif %}
            </div>
        </div>
    </nav>
{% endblock %}

devGrasys/templates/lecturer/change_picture.html
{% extends 'lecturer/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}修改照片{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='jcrop/css/jquery.Jcrop.min.css') }}">
{% endblock %}

{% block content %}
    <div class="card w-100 bg-light">
        <h3 class="card-header">修改照片</h3>
        <div class="card-body">
            {{ render_form(upload_form, action=url_for('lecturer.upload_picture',course_name=course.name)) }}
            <small class="text-muted">
                你的文件大小不得超过 3 MB,允许提交的文件格式为 png 和 jpg。
            </small>
        </div>
        <div class="card-body">
            {{ avatars.crop_box('lecturer.get_avatar', course.avatar_raw) }}
            {{ avatars.preview_box('lecturer.get_avatar', course.avatar_raw) }}
        </div>
        <div class="card-body">
            {{ render_form(crop_form, action=url_for('lecturer.crop_picture',course_name=course.name)) }}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='jcrop/js/jquery.Jcrop.min.js') }}"></script>
    {{ avatars.init_jcrop() }}
{% endblock %}

devGrasys/templates/lecturer/check_homework.html
{% extends 'lecturer/base.html' %}
{% from 'macros.html' import student_card with context %}
{% from 'macros.html' import student_check_card with context %}

{% block title %}检查 - {{ homework.title }} - 讲师{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h3>{{ homework.title }}:</h3>
            <p>{{ homework.description | safe }}</p>
            <h5><span class="oi oi-calendar"></span>
                {{ moment(homework.timestamp).format('LL') }}
                - {{ moment(homework.deadline).format('LL') }}
            </h5>
            <hr/>
            <h3>提交情况：</h3>
            <p><span class="oi oi-task"></span> 已提交人数 / 总人数： {{ submitted_number }}
                / {{ students.count() }}</p>
            <p><span class="oi oi-x"></span> 未提交学生：</p>
            <div class="card bg-light">
                <div class="card-body">
                    {% for student in students %}
                        {% if not student.is_submitted(homework=homework) %}
                            {{ student_card(student=student) }}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <hr/>
            <h3>完成情况：</h3>
            <p>
                <span class="oi oi-star"></span>
                <span class="oi oi-star"></span>
                <span class="oi oi-star"></span>
                A :
            </p>
            <div class="card bg-light">
                <div class="card-body">
                    {% for student in students %}
                        {% if student.is_submitted(homework=homework) %}
                            {% if answers.filter_by(student=student).first().is_a() %}
                                {{ student_check_card(homework=homework,course=course,student=student) }}
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <br/>
            <p>
                <span class="oi oi-star"></span>
                <span class="oi oi-star"></span>
                B :
            </p>
            <div class="card bg-light">
                <div class="card-body">
                    {% for student in students %}
                        {% if student.is_submitted(homework=homework) %}
                            {% if answers.filter_by(student=student).first().is_b() %}
                                {{ student_check_card(homework=homework,course=course,student=student) }}
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <br/>
            <p>
                <span class="oi oi-star"></span>
                C :
            </p>
            <div class="card bg-light">
                <div class="card-body">
                    {% for student in students %}
                        {% if student.is_submitted(homework=homework) %}
                            {% if answers.filter_by(student=student).first().is_c() %}
                                {{ student_check_card(homework=homework,course=course,student=student) }}
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <br/>
            <p>
                <span class="oi oi-arrow-bottom"></span>
                D :
            </p>
            <div class="card bg-light">
                <div class="card-body">
                    {% for student in students %}
                        {% if student.is_submitted(homework=homework) %}
                            {% if answers.filter_by(student=student).first().is_d() %}
                                {{ student_check_card(homework=homework,course=course,student=student) }}
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

devGrasys/templates/lecturer/check_student.html
{% extends 'lecturer/base.html' %}

{% block title %}检查 - {{ homework.title }} - {{ student.name }} - 讲师{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h3>学生名：</h3>
            <p>{{ student.name }}</p>
            <hr/>
            <h3>答案内容：</h3>
            <p>{{ answer.body | safe }}</p>
        </div>
    </div>
{% endblock %}

devGrasys/templates/lecturer/course_students.html
{% extends 'lecturer/view_course.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}
{% from 'macros.html' import student_card with context %}

{% block title %}{{ course.name }} - 学生{% endblock %}

{% block view_content %}
    {% if course.students.count() != 0 %}
        {% for student in course.students.all() %}
            {{ student_card(student=student) }}
        {% endfor %}
    {% else %}
        <div class="tip">
            <h3>尚无学生加入。</h3>
        </div>
    {% endif %}
{% endblock %}

{% block pagination_content %}
    {% if course.students.count() != 0 %}
        <div class="page-footer">
            {{ render_pagination(pagination) }}
        </div>
    {% endif %}
{% endblock %}

devGrasys/templates/lecturer/create_course.html
{% extends 'lecturer/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}创建 - 讲师{% endblock %}

{% block content %}
    <h2>请填写课程信息：</h2>
    <hr />
    <div class="row justify-content-md-center">
        <div class="col-md-8">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

devGrasys/templates/lecturer/edit_course.html
{% extends 'lecturer/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}管理课程信息{% endblock %}

{% block content %}
    <div class="card w-100 bg-light">
        <h3 class="card-header">修改信息</h3>
        <div class="card-body">
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

devGrasys/templates/lecturer/index_lecturer.html
{% extends 'lecturer/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}讲师{% endblock %}

{% block content %}
    {% if current_user.is_authenticated %}
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                <div class="card mb-3 w-100 bg-light">
                    <div class="card-header">
                        <img class="rounded img-fluid avatar-s"
                             src="{{ url_for('lecturer.get_avatar', filename=current_user.avatar_m) }}">
                        <span class="card-title">{{ current_user.name }} -
                            <span class="oi oi-person"> 讲师</span>
                        </span>
                    </div>
                    <div class="card-body">
                        <h4>{{ courses| length }} 你的课程:</h4>
                        <p>(课程名称 - 课程介绍)</p>
                        {% if courses|length ==0 %}
                            <div class="tip">
                                <h3>还没有课程！</h3>
                                <h3>请创建你的课程。</h3>
                            </div>
                        {% else %}
                            {% for course in courses %}
                                <a class="dead-link"
                                   href="{{ url_for('lecturer.view_course', course_name=course.name) }}">
                                    <img src="{{ url_for('lecturer.get_avatar', filename=course.avatar_s) }}">
                                    {{ course.name }} - {{ course.intro }}
                                </a>
                                <hr/>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div class="jumbotron">
            <div class="row">
                <div class="col-md-8">
                    <img src="{{ url_for('static', filename='images/lecturer_reg.jpg') }}" class="rounded img-fluid">
                </div>
                <div class="col-md-4">
                    <div class="card mb-3 w-100 bg-light">
                        <div class="card-header">
                            <h4>欢迎使用！</h4>
                        </div>
                        <div class="card-body">
                            <div class="navbar-nav ml-auto">
                                <a class="btn btn-outline-dark" href="{{ url_for('lecturer.register_lecturer') }}">注册</a>
                            </div>
                            <hr>
                            <small>已经注册了账户？<a href="{{ url_for('lecturer.login_lecturer') }}">点击此处登录
                            </a>
                            </small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

devGrasys/templates/lecturer/login_lecturer.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}讲师 - 登录{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-8">
                <img src="{{ url_for('static', filename='images/lecturer_reg.jpg') }}" class="rounded img-fluid">
            </div>
            <div class="col-md-4">
                <div class="card mb-3 w-100 bg-light">
                    <div class="card-header"><h4>讲师账户</h4></div>
                    <div class="card-body">
                        {{ render_form(form) }}
                        <hr>
                        <p class="small"><a href="{{ url_for('.register_lecturer') }}">注册一个新的账户</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

devGrasys/templates/lecturer/select_course.html
{% extends 'lecturer/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}选择课程 - 讲师{% endblock %}

{% block content %}
    <div class="row justify-content-md-center">
        <div class="col-md-8">
            <div class="card mb-3 w-100 bg-light">
                <div class="card-header">
                    <h4>请选择你的课程：</h4>
                    <p>(课程名称 - 课程介绍)</p>
                </div>
                {% for course in courses %}
                    <div class="card-body">
                        <a class="dead-link"
                           href="{{ url_for('lecturer.view_homework', course_name=course.name) }}">
                            <img src="{{ url_for('lecturer.get_avatar', filename=course.avatar_s) }}">
                            {{ course.name }} - {{ course.intro }}
                        </a>
                    </div>
                    <hr/>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

devGrasys/templates/lecturer/view_course.html
{% extends 'lecturer/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}查看 - {{ course.name }} - 讲师{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-3">
            <a>
                <img src="{{ url_for('lecturer.get_avatar', filename=course.avatar_l) }}" class="rounded img-fluid">
            </a>
        </div>
        <div class="col-md-9">
            <h1>{{ course.name }}</h1>
            <h4><small class="text-muted">{{ course.intro }}</small></h4>
            <div class="float-right">
                <a class="btn btn-outline-dark btn-group-sm"
                   href="{{ url_for('lecturer.edit_course',course_name=course.name ) }}">管理信息
                </a>
                <a class="btn btn-outline-dark btn-group-sm"
                   href="{{ url_for('lecturer.change_picture',course_name=course.name ) }}">修改图片
                </a>
                <form class="inline" method="post"
                      action="{{ url_for('lecturer.end_course', course_name=course.name, next=request.full_path) }}">
                    <button type="submit" class="btn btn-danger btn-group-sm">结课</button>
                </form>
            </div>
        </div>
    </div>

    <div class="user-nav">
        <ul class="nav nav-tabs">
            {{ render_nav_item('lecturer.show_students', '学生', course_name=course.name) }}
            {{ render_nav_item('lecturer.show_assistants', '助教', course_name=course.name) }}
        </ul>
        <div class="row">
            <div class="col-md-12">
                {% block view_content %}{% endblock %}
            </div>
        </div>
        {% block pagination_content %}{% endblock %}
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='jcrop/js/jquery.Jcrop.min.js') }}"></script>
    {{ avatars.init_jcrop() }}
{% endblock %}

devGrasys/templates/lecturer/view_homework.html
{% extends 'lecturer/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}查看 - {{ course.name }} 作业 - 讲师{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h3>已布置作业：</h3>
            <h4>(标题 - 起始时间 - 截止日期)</h4>
            {% for homework in homework_group %}
                <a class="dead-link"
                   href="{{ url_for('lecturer.check_homework', course_name=course.name,homework_title=homework.title) }}">
                    <span class="oi oi-calendar"></span> {{ homework.title }}
                    - {{ moment(homework.timestamp).format('LL') }}
                    - {{ moment(homework.deadline).format('LL') }}
                </a>
                <br \>
            {% endfor %}
        </div>
    </div>
    <hr/>
    <div class="row">
        <div class="col-md-8">
            <h3>布置新的作业：</h3>
            {{ render_form(form) }}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ ckeditor.load() }}
{% endblock %}