devGrasys/forms/assistant.py
# -*- coding: utf-8 -*-
"""
    :author: Jifan Jiang
    :url: https://github.com/fn19980304
"""

from flask_wtf import FlaskForm
from flask_ckeditor import CKEditorField
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import StringField, SubmitField, PasswordField, BooleanField, SelectField, HiddenField
from wtforms.validators import DataRequired, Length, Regexp, EqualTo
from wtforms import ValidationError

from devGrasys.models import Assistant


class LoginFormAssistant(FlaskForm):
    user_id = StringField('UserID', validators=[DataRequired(), Length(10, 10)])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember me')
    submit = SubmitField('Log in')


class RegisterFormAssistant(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(1, 30)])
    user_id = StringField('UserID', validators=[DataRequired(), Length(10, 10), Regexp('^[A][0-9]*$',
                                                                                       message='Lecturer ID should '
                                                                                               'begin with A.')])
    password = PasswordField('Password', validators=[DataRequired(), Length(8, 128), EqualTo('password2')])
    password2 = PasswordField('Confirm password', validators=[DataRequired()])
    submit = SubmitField()

    def validate_user_id(self, field):
        if Assistant.query.filter_by(user_id=field.data).first():
            raise ValidationError('The ID is already in use.')


class CorrectHomeworkForm(FlaskForm):
    body = CKEditorField('Your remark to the answer:', validators=[DataRequired()])
    grade = SelectField('Answer grade:',
                        validators=[DataRequired()],
                        choices=[('A', 'A - Excellent'), ('B', 'B - Well'), ('C', 'C - Qualified'),
                                 ('D', 'D - Unqualified')],
                        )
    submit = SubmitField()


class EditProfileFormAssistant(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(1, 30)])
    submit = SubmitField()


class UploadAvatarFormAssistant(FlaskForm):
    image = FileField('Upload', validators=[
        FileRequired(),
        FileAllowed(['jpg', 'png'], 'The file format should be .jpg or .png.')
    ])
    submit = SubmitField()


class CropAvatarFormAssistant(FlaskForm):
    x = HiddenField()
    y = HiddenField()
    w = HiddenField()
    h = HiddenField()
    submit = SubmitField('Crop and Update')

devGrasys/blueprints/assistant.py
# -*- coding: utf-8 -*-
"""
    :author: Jifan Jiang
    :url: https://github.com/fn19980304
"""

from flask import render_template, flash, redirect, url_for, Blueprint, send_from_directory, current_app
from flask_login import login_user, current_user, login_required, logout_user

from devGrasys.models import Assistant, Course, Lecturer, Homework, Answer, Student, Correct
from devGrasys.forms.assistant import RegisterFormAssistant, LoginFormAssistant, CorrectHomeworkForm, \
    EditProfileFormAssistant, CropAvatarFormAssistant, UploadAvatarFormAssistant
from devGrasys.utils import redirect_back, flash_errors
from devGrasys.extensions import db, avatars

assistant_bp = Blueprint('assistant', __name__)


@assistant_bp.route('/', methods=['GET'])
def index_assistant():
    if current_user.is_authenticated:
        assistant = current_user
        courses = Course.query.all()
        lecturers = Lecturer.query.all()
        return render_template('assistant/index_assistant.html', courses=courses, lecturers=lecturers,
                               assistant=assistant)
    return render_template('assistant/index_assistant.html')


@assistant_bp.route('/login', methods=['GET', 'POST'])
def login_assistant():
    if current_user.is_authenticated:
        return redirect(url_for('assistant.index_assistant'))

    form = LoginFormAssistant()
    if form.validate_on_submit():
        user = Assistant.query.filter_by(user_id=form.user_id.data).first()
        if user is not None and user.validate_password(form.password.data):
            if login_user(user, form.remember_me.data):
                flash('Login success.', 'info')
                return redirect_back()
        flash('Invalid userID or password.', 'warning')

    return render_template('assistant/login_assistant.html', form=form)


@assistant_bp.route('/logout')
@login_required
def logout_assistant():
    logout_user()
    flash('Logout success.', 'info')
    return redirect(url_for('main.index'))


@assistant_bp.route('/register', methods=['GET', 'POST'])
def register_assistant():
    if current_user.is_authenticated:
        return redirect(url_for('assistant.index_assistant'))

    form = RegisterFormAssistant()
    if form.validate_on_submit():
        name = form.name.data
        user_id = form.user_id.data
        password = form.password.data
        user = Assistant(user_id=user_id, name=name)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('assistant.login_assistant'))
    return render_template('assistant/register_assistant.html', form=form)


@assistant_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@assistant_bp.route('/<course_name>')
def view_course(course_name):
    assistant = current_user
    course = Course.query.filter_by(name=course_name).first_or_404()
    lecturer = Lecturer.query.filter_by(name=course.lecturer_name).first_or_404()
    return render_template('assistant/view_course.html', course=course, assistant=assistant, lecturer=lecturer)


@assistant_bp.route('/<course_name>/join', methods=['POST'])
def join_course(course_name):
    assistant = current_user
    course = Course.query.filter_by(name=course_name).first_or_404()
    if course.assistant_is_joined(assistant=assistant):
        flash('Already joined.', 'info')
        return redirect_back()

    course.assistant_join(assistant)
    flash('Course joined.', 'success')
    return redirect_back()


@assistant_bp.route('/<course_name>/quit', methods=['POST'])
def quit_course(course_name):
    assistant = current_user
    course = Course.query.filter_by(name=course_name).first_or_404()
    if not course.assistant_is_joined(assistant=assistant):
        flash('Not joined yet.', 'info')
        return redirect_back()

    course.assistant_quit(assistant)
    flash('Course quoted.', 'success')
    return redirect_back()


@assistant_bp.route('/select', methods=['GET'])
def select_course():
    assistant = current_user
    courses = Course.query.all()
    return render_template('assistant/select_course.html', courses=courses, assistant=assistant)


@assistant_bp.route('/select/<course_name>', methods=['GET'])
def view_list(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    homework_group = Homework.query.filter_by(course=course)
    return render_template('assistant/view_list.html', course=course, homework_group=homework_group)


@assistant_bp.route('/select/<course_name>/<homework_title>', methods=['GET'])
def view_homework(course_name, homework_title):
    course = Course.query.filter_by(name=course_name).first_or_404()
    homework = Homework.query.filter_by(course=course).filter_by(title=homework_title).first_or_404()
    answers = Answer.query.filter_by(homework=homework)
    return render_template('assistant/view_homework.html', course=course, homework=homework, answers=answers)


@assistant_bp.route('/select/<course_name>/<homework_title>/<student_name>', methods=['GET', 'POST'])
def correct_homework(course_name, homework_title, student_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    homework = Homework.query.filter_by(course=course).filter_by(title=homework_title).first_or_404()
    student = Student.query.filter_by(name=student_name).first_or_404()
    answer = Answer.query.filter_by(homework=homework).filter_by(student=student).first_or_404()
    form = CorrectHomeworkForm()
    if not answer.is_corrected() and form.validate_on_submit():
        body = form.body.data
        grade = form.grade.data
        correct = Correct(body=body, grade=grade)
        homework.corrects.append(correct)
        answer.correct.append(correct)
        db.session.add(correct)
        db.session.commit()
        return redirect_back(
            url_for('assistant.view_homework', course_name=course.name, homework_title=homework.title))
    correct = Correct.query.filter_by(answer=answer).first()
    return render_template('assistant/correct_homework.html', correct=correct, answer=answer, student=student,
                           homework=homework,
                           form=form)


@assistant_bp.route('/settings/profile', methods=['GET', 'POST'])
def edit_profile():
    form = EditProfileFormAssistant()
    if form.validate_on_submit():
        current_user.name = form.name.data
        db.session.commit()
        flash('Profile updated.', 'success')
        return redirect(url_for('assistant.index_assistant'))
    form.name.data = current_user.name
    return render_template('assistant/settings/edit_profile.html', form=form)


@assistant_bp.route('/settings/avatar')
def change_avatar():
    upload_form = UploadAvatarFormAssistant()
    crop_form = CropAvatarFormAssistant()
    return render_template('assistant/settings/change_avatar.html', upload_form=upload_form, crop_form=crop_form)


@assistant_bp.route('/settings/avatar/upload', methods=['POST'])
def upload_avatar():
    form = UploadAvatarFormAssistant()
    if form.validate_on_submit():
        image = form.image.data
        filename = avatars.save_avatar(image)
        current_user.avatar_raw = filename
        db.session.commit()
        flash('Image uploaded, please crop.', 'success')
    flash_errors(form)
    return redirect(url_for('.change_avatar'))


@assistant_bp.route('/settings/avatar/crop', methods=['POST'])
def crop_avatar():
    form = CropAvatarFormAssistant()
    if form.validate_on_submit():
        x = form.x.data
        y = form.y.data
        w = form.w.data
        h = form.h.data
        filenames = avatars.crop_avatar(current_user.avatar_raw, x, y, w, h)
        current_user.avatar_s = filenames[0]
        current_user.avatar_m = filenames[1]
        current_user.avatar_l = filenames[2]
        db.session.commit()
        flash('Avatar updated.', 'success')
    flash_errors(form)
    return redirect(url_for('.change_avatar'))

devGrasys/templates/assistant/base.html
{% extends 'base.html' %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('assistant.index_assistant') }}">
                <img src="{{ url_for('static', filename='favicon_index.ico') }}" alt="devGrasys">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <div class="navbar-nav mr-auto">
                    {% if current_user.is_authenticated %}
                        {{ render_nav_item('assistant.index_assistant', 'Home') }}
                        {{ render_nav_item('assistant.select_course', 'View / Correct') }}
                    {% else %}
                        {{ render_nav_item('assistant.index_assistant', 'Home') }}
                    {% endif %}
                </div>
            </div>
            <div class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                    <div class="dropdown nav-item">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">
                            <img class="avatar-xs"
                                 src="{{ url_for('assistant.get_avatar', filename=current_user.avatar_s) }}">
                            <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" role="menu">
                            <h6 class="dropdown-header">Logged in as {{ current_user.name }}</h6>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('assistant.edit_profile') }}">
                                <span class="oi oi-cog"></span> Settings
                            </a>
                            <a class="dropdown-item" href="{{ url_for('assistant.logout_assistant') }}">
                                <span class="oi oi-power-standby"></span> Logout
                            </a>
                        </div>
                    </div>
                {% else %}
                {% endif %}
            </div>
        </div>
    </nav>
{% endblock %}

devGrasys/templates/assistant/correct_homework.html
{% extends 'assistant/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}View / Correct - {{ homework.title }} - {{ student.name }} - Assistant{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h3>Student name:</h3>
            <p>{{ student.name }}</p>
            <hr/>
            <h3>Answer content:</h3>
            <p>{{ answer.body | safe }}</p>
            <hr/>
            {% if answer.is_corrected() %}
                <h3>Your remark:</h3>
                <p>{{ correct.body | safe }}</p>
                <hr/>
                <h3>The grade:</h3>
                <p>{{ correct.grade }}</p>
            {% else %}
                <h3>Correct the answer:</h3>
                {{ render_form(form) }}
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ ckeditor.load() }}
{% endblock %}

devGrasys/templates/assistant/index_assistant.html
{% extends 'assistant/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Assistant{% endblock %}

{% block content %}
    {% if current_user.is_authenticated %}
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                <div class="card mb-3 w-100 bg-light">
                    <div class="card-header">
                        <img class="rounded img-fluid avatar-s"
                             src="{{ url_for('assistant.get_avatar', filename=current_user.avatar_m) }}">
                        <span class="card-title">{{ current_user.name }} -
                            <span class="oi oi-person"> Assistant</span>
                        </span>
                    </div>
                    {% if courses|length ==0 %}
                        <div class="tip">
                            <h3>No course yet!</h3>
                            <h3>Please wait.</h3>
                        </div>
                    {% else %}
                        <div class="card-body">
                            <h3>The courses you can join:</h3>
                            <p>(course name - course lecturer - course introduction)</p>
                            {% for course in courses %}
                                {% if not course.assistant_is_joined(assistant) %}
                                    <a class="dead-link"
                                       href="{{ url_for('assistant.view_course', course_name=course.name) }}">
                                        <img src="{{ url_for('assistant.get_avatar', filename=course.avatar_s) }}">
                                        {{ course.name }} - {{ course.lecturer_name }} - {{ course.intro }}
                                    </a>
                                    <hr/>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div class="card-body">
                            <h3>The courses you have already joined:</h3>
                            <p>(course name - course lecturer - course introduction)</p>
                            {% if assistant.courses.count() != 0 %}
                                {% for course in courses %}
                                    {% if course.assistant_is_joined(assistant) %}
                                        <a class="dead-link"
                                           href="{{ url_for('assistant.view_course', course_name=course.name) }}">
                                            <img src="{{ url_for('assistant.get_avatar', filename=course.avatar_s) }}">
                                            {{ course.name }} - {{ course.lecturer_name }} - {{ course.intro }}
                                        </a>
                                        <hr/>
                                    {% endif %}
                                {% endfor %}
                            {% else %}
                                <div class="tip">
                                    <h3>Please join the course.</h3>
                                </div>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {% else %}
        <div class="jumbotron">
            <div class="row">
                <div class="col-md-8">
                    <img src="{{ url_for('static', filename='images/assistant_reg.jfif') }}" class="rounded img-fluid">
                </div>
                <div class="col-md-4">
                    <div class="card mb-3 w-100 bg-light">
                        <div class="card-header">
                            <h4>Welcome to use!</h4>
                        </div>
                        <div class="card-body">
                            <div class="navbar-nav ml-auto">
                                <a class="btn btn-outline-dark" href="{{ url_for('assistant.register_assistant') }}">Join
                                    Now</a>
                            </div>
                            <hr>
                            <small>Already have an account? <a href="{{ url_for('assistant.login_assistant') }}">Click
                                here to
                                log in.</a>
                            </small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

devGrasys/templates/assistant/login_assistant.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Assistant - Login{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-8">
                <img src="{{ url_for('static', filename='images/assistant_reg.jfif') }}" class="rounded img-fluid">
            </div>
            <div class="col-md-4">
                <div class="card mb-3 w-100 bg-light">
                    <div class="card-header"><h4>Assistant Account</h4></div>
                    <div class="card-body">
                        {{ render_form(form) }}
                        <hr>
                        <p class="small"><a href="{{ url_for('.register_assistant') }}">Register new account</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

devGrasys/templates/assistant/register_assistant.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Assistant - Register{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-8">
                <h3>For assistants , you can:</h3>
                <p>Check the homework list that the students submitted.</p>
                <p>Submit your correction results.</p>
                <hr />
                <p>P.S. Your UserID should begin with A ,followed by 9 digits.</p>
                <img src="{{ url_for('static', filename='images/assistant_reg.jfif') }}" class="rounded img-fluid">
            </div>
            <div class="col-md-4">
                <div class="card mb-3 w-100 bg-light">
                    <div class="card-header">
                        <h4>Assistant Account</h4>
                    </div>
                    <div class="card-body">
                        <div class="navbar-nav ml-auto">
                            {{ render_form(form) }}
                        </div>
                        <hr>
                        <small>Already have an account? <a href="{{ url_for('.login_assistant') }}">Click here to log in.</a>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

devGrasys/templates/assistant/select_course.html
{% extends 'assistant/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}Select Course - Assistant{% endblock %}

{% block content %}
    <div class="row justify-content-md-center">
        <div class="col-md-8">
            <div class="card mb-3 w-100 bg-light">
                <div class="card-header">
                    <h4>Please select the course:</h4>
                    <p>(course name - lecturer - course introduction)</p>
                </div>
                {% if assistant.courses.count() !=0 %}
                    {% for course in courses %}
                        <div class="card-body">
                            {% if course.assistant_is_joined(assistant) %}
                                <a class="dead-link"
                                   href="{{ url_for('assistant.view_list', course_name=course.name) }}">
                                    <img src="{{ url_for('assistant.get_avatar', filename=course.avatar_s) }}">
                                    {{ course.name }} - {{ course.lecturer_name }} - {{ course.intro }}
                                </a>
                            {% endif %}
                        </div>
                        <hr/>
                    {% endfor %}
                {% else %}
                    <div class="tip">
                        <h3>Please join the course.</h3>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

devGrasys/templates/assistant/view_course.html
{% extends 'assistant/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}View - {{ course.name }} - Assistant{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-3">
            <a>
                <img src="{{ url_for('assistant.get_avatar', filename=course.avatar_l) }}" class="rounded img-fluid">
            </a>
        </div>
        <div class="col-md-9">
            <h1>{{ course.name }}</h1>
            <h3>
                <img src="{{ url_for('lecturer.get_avatar', filename=lecturer.avatar_s) }}" class="rounded img-fluid">
                {{ lecturer.name }}
            </h3>
            <h4><small class="text-muted">{{ course.intro }}</small></h4>
            <div class="float-right">
                {% if course.assistant_is_joined(assistant) %}
                    <form class="inline" method="post"
                          action="{{ url_for('assistant.quit_course', course_name=course.name, next=request.full_path) }}">
                        <button type="submit" class="btn btn-outline-danger btn-group-sm">Quit</button>
                    </form>
                {% else %}
                    <form class="inline" method="post"
                          action="{{ url_for('assistant.join_course', course_name=course.name, next=request.full_path) }}">
                        <button type="submit" class="btn btn-outline-dark btn-group-sm">Join</button>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

devGrasys/templates/assistant/view_homework.html
{% extends 'assistant/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}View / Correct - {{ homework.title }} - Assistant{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h3>{{ homework.title }}:</h3>
            <h5>{{ homework.description | safe }}</h5>
            <h5><span class="oi oi-calendar"></span>
                {{ moment(homework.timestamp).format('LL') }}
                - {{ moment(homework.deadline).format('LL') }}
            </h5>
            <hr/>
            <h3>Submitted homework answers:</h3>
            <h5>(student name - submitted time)</h5>
            {% for answer in answers %}
                <a class="dead-link"
                   href="{{ url_for('assistant.correct_homework', course_name=course.name,homework_title=homework.title,student_name=answer.student.name) }}">
                    <span class="oi oi-clock"></span> {{ answer.student.name }}
                    - {{ moment(answer.timestamp).format('LL') }}
                </a>
                {% if answer.is_corrected() %}
                    <span class="oi oi-check"></span>
                {% else %}
                    <span class="oi oi-x"></span>
                {% endif %}
                <br/>
            {% endfor %}
        </div>
    </div>
{% endblock %}

devGrasys/templates/assistant/view_list.html
{% extends 'assistant/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}View - {{ course.name }} Homework - Assistant{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h3>Homework list:</h3>
            <h4>(title - starting time - deadline)</h4>
            {% for homework in homework_group %}
                <a class="dead-link"
                   href="{{ url_for('assistant.view_homework', course_name=course.name,homework_title=homework.title) }}">
                    <span class="oi oi-calendar"></span> {{ homework.title }}
                    - {{ moment(homework.timestamp).format('LL') }}
                    - {{ moment(homework.deadline).format('LL') }}
                </a>
                <br \>
            {% endfor %}
        </div>
    </div>
{% endblock %}