devGrasys/blueprints/lecturer.py
# -*- coding: utf-8 -*-
"""
    :author: Jifan Jiang
    :url: https://github.com/fn19980304
"""
from datetime import datetime

from flask import render_template, flash, redirect, url_for, Blueprint, send_from_directory, current_app, request
from flask_login import login_required, login_user, logout_user, current_user

from devGrasys.models import Lecturer, Course, Homework, Student, Answer
from devGrasys.forms.lecturer import RegisterFormLecturer, LoginFormLecturer, CreateCourseForm, AdminCourseForm, \
    AssignHomeworkForm, EditProfileFormLecturer, CropAvatarFormLecturer, UploadAvatarFormLecturer
from devGrasys.utils import redirect_back, flash_errors
from devGrasys.extensions import db, avatars

lecturer_bp = Blueprint('lecturer', __name__)


@lecturer_bp.route('/', methods=['GET'])
def index_lecturer():
    if current_user.is_authenticated:
        user = current_user
        courses = Course.query.filter_by(lecturer=user).all()
        return render_template('lecturer/index_lecturer.html', courses=courses)
    return render_template('lecturer/index_lecturer.html')


@lecturer_bp.route('/login', methods=['GET', 'POST'])
def login_lecturer():
    if current_user.is_authenticated:
        return redirect(url_for('lecturer.index_lecturer'))

    form = LoginFormLecturer()
    if form.validate_on_submit():
        user = Lecturer.query.filter_by(user_id=form.user_id.data).first()
        if user is not None and user.validate_password(form.password.data):
            if login_user(user, form.remember_me.data):
                flash('登录成功。', 'info')
                return redirect_back()
        flash('ID或密码不正确。', 'warning')

    return render_template('lecturer/login_lecturer.html', form=form)


@lecturer_bp.route('/logout')
@login_required
def logout_lecturer():
    logout_user()
    flash('注销成功。', 'info')
    return redirect(url_for('main.index'))


@lecturer_bp.route('/register', methods=['GET', 'POST'])
def register_lecturer():
    if current_user.is_authenticated:
        return redirect(url_for('lecturer.index_lecturer'))

    form = RegisterFormLecturer()
    if form.validate_on_submit():
        name = form.name.data
        user_id = form.user_id.data
        password = form.password.data
        user = Lecturer(user_id=user_id, name=name)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('lecturer.login_lecturer'))
    return render_template('lecturer/register_lecturer.html', form=form)


@lecturer_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@lecturer_bp.route('/create', methods=['GET', 'POST'])
def create_course():
    form = CreateCourseForm()
    lecturer = current_user
    if form.validate_on_submit():
        name = form.name.data
        intro = form.intro.data
        lecturer_name = lecturer.name
        course = Course(name=name, intro=intro, lecturer_name=lecturer_name)
        lecturer.courses.append(course)
        db.session.add(course)
        db.session.commit()
        return redirect(url_for('lecturer.index_lecturer'))
    return render_template('lecturer/create_course.html', form=form)


@lecturer_bp.route('/<course_name>')
def view_course(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    return render_template('lecturer/view_course.html', course=course)


@lecturer_bp.route('/<course_name>/end', methods=['POST'])
def end_course(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    db.session.delete(course)
    db.session.commit()
    flash('课程结束。', 'success')
    return redirect(url_for('lecturer.index_lecturer'))


@lecturer_bp.route('/<course_name>/students')
def show_students(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['USER_PER_PAGE']
    pagination = course.students.paginate(page, per_page)
    students = pagination.items
    return render_template('lecturer/course_students.html', course=course, pagination=pagination, students=students)


@lecturer_bp.route('/<course_name>/assistants')
def show_assistants(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['USER_PER_PAGE']
    pagination = course.assistants.paginate(page, per_page)
    assistants = pagination.items
    return render_template('lecturer/course_assistants.html', course=course, pagination=pagination,
                           assistants=assistants)


@lecturer_bp.route('/<course_name>/admin', methods=['GET', 'POST'])
def edit_course(course_name):
    form = AdminCourseForm()
    course = Course.query.filter_by(name=course_name).first_or_404()
    if form.validate_on_submit():
        course.name = form.name.data
        course.intro = form.intro.data
        db.session.commit()
        flash('上传成功。', 'success')
        return redirect(url_for('lecturer.view_course', course_name=course.name))
    form.name.data = course.name
    form.intro.data = course.intro
    return render_template('lecturer/edit_course.html', form=form)


@lecturer_bp.route('/<course_name>/picture')
def change_picture(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    upload_form = UploadAvatarFormLecturer()
    crop_form = CropAvatarFormLecturer()
    return render_template('lecturer/change_picture.html', course=course, upload_form=upload_form, crop_form=crop_form)


@lecturer_bp.route('/<course_name>/picture/upload', methods=['POST'])
def upload_picture(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    form = UploadAvatarFormLecturer()
    if form.validate_on_submit():
        image = form.image.data
        filename = avatars.save_avatar(image)
        course.avatar_raw = filename
        db.session.commit()
        flash('图片上传成功, 请裁剪。', 'success')
    flash_errors(form)
    return redirect(url_for('lecturer.change_picture', course_name=course.name))


@lecturer_bp.route('/<course_name>/picture/crop', methods=['POST'])
def crop_picture(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    form = CropAvatarFormLecturer()
    if form.validate_on_submit():
        x = form.x.data
        y = form.y.data
        w = form.w.data
        h = form.h.data
        filenames = avatars.crop_avatar(course.avatar_raw, x, y, w, h)
        course.avatar_s = filenames[0]
        course.avatar_m = filenames[1]
        course.avatar_l = filenames[2]
        db.session.commit()
        flash('上传成功。', 'success')
    flash_errors(form)
    return redirect(url_for('lecturer.change_picture', course_name=course.name))


@lecturer_bp.route('/select', methods=['GET'])
def select_course():
    user = current_user
    courses = Course.query.filter_by(lecturer=user).all()
    return render_template('lecturer/select_course.html', courses=courses)


@lecturer_bp.route('/select/<course_name>', methods=['GET', 'POST'])
def view_homework(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    homework_group = Homework.query.filter_by(course=course)
    form = AssignHomeworkForm()
    current_time = datetime.utcnow()
    if form.validate_on_submit():
        title = form.title.data
        description = form.description.data
        deadline = form.deadline.data
        new_homework = Homework(title=title, description=description, deadline=deadline)
        course.homework_group.append(new_homework)
        db.session.add(new_homework)
        db.session.commit()
        return redirect(url_for('lecturer.view_homework', course_name=course.name))
    return render_template('lecturer/view_homework.html', course=course, homework_group=homework_group, form=form,
                           current_time=current_time)


@lecturer_bp.route('/select/<course_name>/<homework_title>', methods=['GET'])
def check_homework(course_name, homework_title):
    course = Course.query.filter_by(name=course_name).first_or_404()
    students = course.students
    homework = Homework.query.filter_by(course=course).filter_by(title=homework_title).first_or_404()
    answers = homework.answers
    submitted_number = 0
    for student in students:
        if student.is_submitted(homework=homework):
            submitted_number += 1
    return render_template('lecturer/check_homework.html', course=course, homework=homework, students=students,
                           answers=answers,
                           submitted_number=submitted_number)


@lecturer_bp.route('/select/<course_name>/<homework_title>/<student_name>', methods=['GET'])
def check_student(course_name, homework_title, student_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    homework = Homework.query.filter_by(course=course).filter_by(title=homework_title).first_or_404()
    student = Student.query.filter_by(name=student_name).first_or_404()
    answer = Answer.query.filter_by(homework=homework).filter_by(student=student).first_or_404()
    return render_template('lecturer/check_student.html', homework=homework, answer=answer, student=student)


@lecturer_bp.route('/settings/profile', methods=['GET', 'POST'])
def edit_profile():
    form = EditProfileFormLecturer()
    if form.validate_on_submit():
        current_user.name = form.name.data
        db.session.commit()
        flash('信息更新。', 'success')
        return redirect(url_for('lecturer.index_lecturer'))
    form.name.data = current_user.name
    return render_template('lecturer/settings/edit_profile.html', form=form)


@lecturer_bp.route('/settings/avatar')
def change_avatar():
    upload_form = UploadAvatarFormLecturer()
    crop_form = CropAvatarFormLecturer()

devGrasys/blueprints/student.py
# -*- coding: utf-8 -*-
"""
    :author: Jifan Jiang
    :url: https://github.com/fn19980304
"""

from flask import render_template, flash, redirect, url_for, Blueprint, send_from_directory, current_app
from flask_login import login_user, current_user, login_required, logout_user

from devGrasys.models import Student, Course, Homework, Answer, Correct, Lecturer
from devGrasys.forms.student import RegisterFormStudent, LoginFormStudent, AnswerForm, EditProfileFormStudent, \
    UploadAvatarFormStudent, CropAvatarFormStudent
from devGrasys.utils import redirect_back, flash_errors
from devGrasys.extensions import db, avatars

student_bp = Blueprint('student', __name__)


@student_bp.route('', methods=['GET'])
def index_student():
    if current_user.is_authenticated:
        student = current_user
        courses = Course.query.all()
        return render_template('student/index_student.html', courses=courses, student=student)
    return render_template('student/index_student.html')


@student_bp.route('/login', methods=['GET', 'POST'])
def login_student():
    if current_user.is_authenticated:
        return redirect(url_for('student.index_student'))

    form = LoginFormStudent()
    if form.validate_on_submit():
        user = Student.query.filter_by(user_id=form.user_id.data).first()
        if user is not None and user.validate_password(form.password.data):
            if login_user(user, form.remember_me.data):
                flash('登录成功。', 'info')
                return redirect_back()
        flash('ID或密码不正确。', 'warning')

    return render_template('student/login_student.html', form=form)


@student_bp.route('/logout')
@login_required
def logout_student():
    logout_user()
    flash('注销成功。', 'info')
    return redirect(url_for('main.index'))


@student_bp.route('/register', methods=['GET', 'POST'])
def register_student():
    if current_user.is_authenticated:
        return redirect(url_for('student.index_student'))

    form = RegisterFormStudent()
    if form.validate_on_submit():
        name = form.name.data
        user_id = form.user_id.data
        password = form.password.data
        user = Student(user_id=user_id, name=name)
        user.set_password(password)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('student.login_student'))
    return render_template('student/register_student.html', form=form)


@student_bp.route('/avatars/<path:filename>')
def get_avatar(filename):
    return send_from_directory(current_app.config['AVATARS_SAVE_PATH'], filename)


@student_bp.route('/<course_name>')
def view_course(course_name):
    student = current_user
    course = Course.query.filter_by(name=course_name).first_or_404()
    lecturer = Lecturer.query.filter_by(name=course.lecturer_name).first_or_404()
    return render_template('student/view_course.html', course=course, student=student, lecturer=lecturer)


@student_bp.route('/<course_name>/join', methods=['POST'])
def join_course(course_name):
    student = current_user
    course = Course.query.filter_by(name=course_name).first_or_404()
    if course.student_is_joined(student=student):
        flash('已加入。', 'info')
        return redirect_back()

    course.student_join(student)
    flash('加入成功。', 'success')
    return redirect_back()


@student_bp.route('/<course_name>/quit', methods=['POST'])
def quit_course(course_name):
    student = current_user
    course = Course.query.filter_by(name=course_name).first_or_404()
    if not course.student_is_joined(student=student):
        flash('尚未加入。', 'info')
        return redirect_back()

    course.student_quit(student)
    flash('退出成功。', 'success')
    return redirect_back()


@student_bp.route('/select', methods=['GET'])
def select_course():
    student = current_user
    courses = Course.query.all()
    return render_template('student/select_course.html', courses=courses, student=student)


@student_bp.route('/select/<course_name>', methods=['GET'])
def view_list(course_name):
    course = Course.query.filter_by(name=course_name).first_or_404()
    homework_group = Homework.query.filter_by(course=course)
    student = current_user
    return render_template('student/view_list.html', student=student, course=course, homework_group=homework_group)


@student_bp.route('/select/<course_name>/<homework_title>', methods=['GET', 'POST'])
def view_homework(course_name, homework_title):
    student = current_user
    course = Course.query.filter_by(name=course_name).first_or_404()
    homework = Homework.query.filter_by(course=course).filter_by(title=homework_title).first_or_404()
    form = AnswerForm()
    if not homework.is_answered(student=student) and form.validate_on_submit():
        body = form.body.data
        answer = Answer(body=body)
        homework.answers.append(answer)
        student.answers.append(answer)
        db.session.add(answer)
        db.session.commit()
        return redirect(url_for('student.view_homework', course_name=course.name, homework_title=homework.title))
    answer = homework.answers.filter_by(student=student).first()
    correct = Correct.query.filter_by(answer=answer).first()
    return render_template('student/view_homework.html', homework=homework, student=student, answer=answer,
                           correct=correct, form=form)


@student_bp.route('/settings/profile', methods=['GET', 'POST'])
def edit_profile():
    form = EditProfileFormStudent()
    if form.validate_on_submit():
        current_user.name = form.name.data
        db.session.commit()
        flash('信息更新。', 'success')
        return redirect(url_for('student.index_student'))
    form.name.data = current_user.name
    return render_template('student/settings/edit_profile.html', form=form)


@student_bp.route('/settings/avatar')
def change_avatar():
    upload_form = UploadAvatarFormStudent()
    crop_form = CropAvatarFormStudent()
    return render_template('student/settings/change_avatar.html', upload_form=upload_form, crop_form=crop_form)


@student_bp.route('/settings/avatar/upload', methods=['POST'])
def upload_avatar():
    form = UploadAvatarFormStudent()
    if form.validate_on_submit():
        image = form.image.data
        filename = avatars.save_avatar(image)
        current_user.avatar_raw = filename
        db.session.commit()
        flash('图片上传成功, 请裁剪。', 'success')
    flash_errors(form)
    return redirect(url_for('.change_avatar'))


@student_bp.route('/settings/avatar/crop', methods=['POST'])
def crop_avatar():
    form = CropAvatarFormStudent()
    if form.validate_on_submit():
        x = form.x.data
        y = form.y.data
        w = form.w.data
        h = form.h.data
        filenames = avatars.crop_avatar(current_user.avatar_raw, x, y, w, h)
        current_user.avatar_s = filenames[0]
        current_user.avatar_m = filenames[1]
        current_user.avatar_l = filenames[2]
        db.session.commit()
        flash('头像上传成功。', 'success')
    flash_errors(form)
    return redirect(url_for('.change_avatar'))

devGrasys/templates/student/base.html
{% extends 'base.html' %}

{% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" href="{{ url_for('student.index_student') }}">
                <img src="{{ url_for('static', filename='favicon_index.ico') }}" alt="devGrasys">
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <div class="navbar-nav mr-auto">
                    {% if current_user.is_authenticated %}
                        {{ render_nav_item('student.index_student', '主页') }}
                        {{ render_nav_item('student.select_course', '查看 / 答题') }}
                    {% else %}
                        {{ render_nav_item('student.index_student', '主页') }}
                    {% endif %}
                </div>
            </div>
            <div class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                    <div class="dropdown nav-item">
                        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                           aria-expanded="false">
                            <img class="avatar-xs"
                                 src="{{ url_for('student.get_avatar', filename=current_user.avatar_s) }}">
                            <span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" role="menu">
                            <h6 class="dropdown-header">以 {{ current_user.name }} 登录</h6>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ url_for('student.edit_profile') }}">
                                <span class="oi oi-cog"></span> 个人设置
                            </a>
                            <a class="dropdown-item" href="{{ url_for('student.logout_student') }}">
                                <span class="oi oi-power-standby"></span> 注销
                            </a>
                        </div>
                    </div>
                {% else %}
                {% endif %}
            </div>
        </div>
    </nav>
{% endblock %}

devGrasys/templates/student/index_student.html
{% extends 'student/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}学生{% endblock %}

{% block content %}
    {% if current_user.is_authenticated %}
        <div class="row justify-content-md-center">
            <div class="col-md-8">
                <div class="card mb-3 w-100 bg-light">
                    <div class="card-header">
                        <img class="rounded img-fluid avatar-s"
                             src="{{ url_for('student.get_avatar', filename=current_user.avatar_m) }}">
                        <span class="card-title">{{ current_user.name }} -
                            <span class="oi oi-person"> 学生</span>
                        </span>
                    </div>
                    {% if courses|length ==0 %}
                        <div class="tip">
                            <h3>暂时还没有课程！</h3>
                            <h3>请等待讲师创建。</h3>
                        </div>
                    {% else %}
                        <div class="card-body">
                            <h3>你现在可以加入的课程：</h3>
                            <p>(课程名称 - 讲师名 - 课程介绍)</p>
                            {% for course in courses %}
                                {% if not course.student_is_joined(student) %}
                                    <a class="dead-link"
                                       href="{{ url_for('student.view_course', course_name=course.name) }}">
                                        <img src="{{ url_for('student.get_avatar', filename=course.avatar_s) }}">
                                        {{ course.name }} - {{ course.lecturer_name }} - {{ course.intro }}
                                    </a>
                                    <hr/>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div class="card-body">
                            <h3>你已经加入的课程：</h3>
                            <p>(课程名称 - 讲师名 - 课程介绍)</p>
                            {% if student.courses.count() != 0 %}
                                {% for course in courses %}
                                    {% if course.student_is_joined(student) %}
                                        <a class="dead-link"
                                           href="{{ url_for('student.view_course', course_name=course.name) }}">
                                            <img src="{{ url_for('student.get_avatar', filename=course.avatar_s) }}">
                                            {{ course.name }} - {{ course.lecturer_name }} - {{ course.intro }}
                                        </a>
                                        <hr/>
                                    {% endif %}
                                {% endfor %}
                            {% else %}
                                <div class="tip">
                                    <h3>请加入一个课程。</h3>
                                </div>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    {% else %}
        <div class="jumbotron">
            <div class="row">
                <div class="col-md-8">
                    <img src="{{ url_for('static', filename='images/student_reg.jpg') }}"
                         class="rounded img-fluid">
                </div>
                <div class="col-md-4">
                    <div class="card mb-3 w-100 bg-light">
                        <div class="card-header">
                            <h4>欢迎使用！</h4>
                        </div>
                        <div class="card-body">
                            <div class="navbar-nav ml-auto">
                                <a class="btn btn-outline-dark"
                                   href="{{ url_for('student.register_student') }}">
                                    注册
                                </a>
                            </div>
                            <hr>
                            <small>已经注册了账户？ <a href="{{ url_for('student.login_student') }}">点击此处登录</a>
                            </small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

devGrasys/templates/student/login_student.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}学生 - 登录{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-8">
                <img src="{{ url_for('static', filename='images/student_reg.jpg') }}" class="rounded img-fluid">
            </div>
            <div class="col-md-4">
                <div class="card mb-3 w-100 bg-light">
                    <div class="card-header"><h4>学生账户</h4></div>
                    <div class="card-body">
                        {{ render_form(form) }}
                        <hr>
                        <p class="small"><a href="{{ url_for('.register_student') }}">注册一个新的账户</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

devGrasys/templates/student/register_student.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}学生 - 注册{% endblock %}

{% block content %}
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-8">
                <h3>学生们可以使用本系统完成：</h3>
                <p><span class="oi oi-check"></span> 查看作业列表</p>
                <p><span class="oi oi-cloud-upload"></span> 提交你的作业答案</p>
                <p><span class="oi oi-circle-check"></span> 查看你的作业批改结果</p>
                <hr />
                <p><span class="oi oi-warning"></span> 注：你的ID必须以S开头，后接9位数字</p>
                <img src="{{ url_for('static', filename='images/student_reg.jpg') }}" class="rounded img-fluid">
            </div>
            <div class="col-md-4">
                <div class="card mb-3 w-100 bg-light">
                    <div class="card-header">
                        <h4>学生账户</h4>
                    </div>
                    <div class="card-body">
                        <div class="navbar-nav ml-auto">
                            {{ render_form(form) }}
                        </div>
                        <hr>
                        <small>已经注册了账户？ <a href="{{ url_for('student.login_student') }}">点击此处登录</a>
                        </small>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

devGrasys/templates/student/select_course.html
{% extends 'student/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}选择课程 - 学生{% endblock %}

{% block content %}
    <div class="row justify-content-md-center">
        <div class="col-md-8">
            <div class="card mb-3 w-100 bg-light">
                <div class="card-header">
                    <h4>请选择课程：</h4>
                    <p>(课程名称 - 讲师名 - 课程介绍)</p>
                </div>
                {% if student.courses.count() !=0 %}
                    {% for course in courses %}
                        <div class="card-body">
                            {% if course.student_is_joined(student) %}
                                <a class="dead-link"
                                   href="{{ url_for('student.view_list', course_name=course.name) }}">
                                    <img src="{{ url_for('student.get_avatar', filename=course.avatar_s) }}">
                                    {{ course.name }} - {{ course.lecturer_name }} - {{ course.intro }}
                                </a>
                                <hr/>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="tip">
                        <h3>请加入一个课程。</h3>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

devGrasys/templates/student/view_course.html
{% extends 'student/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}查看 - {{ course.name }} - 学生{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-3">
            <a>
                <img src="{{ url_for('student.get_avatar', filename=course.avatar_l) }}" class="rounded img-fluid">
            </a>
        </div>
        <div class="col-md-9">
            <h1>{{ course.name }}</h1>
            <h3>
                <img src="{{ url_for('lecturer.get_avatar', filename=lecturer.avatar_s) }}" class="rounded img-fluid">
                {{ lecturer.name }}
            </h3>
            <h4><small class="text-muted">{{ course.intro }}</small></h4>
            <div class="float-right">
                {% if course.student_is_joined(student) %}
                    <form class="inline" method="post"
                          action="{{ url_for('student.quit_course', course_name=course.name, next=request.full_path) }}">
                        <button type="submit" class="btn btn-outline-danger btn-group-sm">退出</button>
                    </form>
                {% else %}
                    <form class="inline" method="post"
                          action="{{ url_for('student.join_course', course_name=course.name, next=request.full_path) }}">
                        <button type="submit" class="btn btn-outline-dark btn-group-sm">加入</button>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

devGrasys/templates/student/view_homework.html
{% extends 'student/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}查看 / 答题 - {{ homework.title }} - 学生{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h3>{{ homework.title }}:</h3>
            <h5>{{ homework.description | safe }}</h5>
            <hr/>
            {% if homework.is_answered(student) %}
                <h3>你的答案：</h3>
                <p>{{ answer.body | safe }}</p>
                <hr/>
                <h3>批改结果：</h3>
                {% if answer.is_corrected() %}
                    <h4>助教评语：</h4>
                    <p>{{ correct.body | safe }}</p>
                    <h4>你的成绩：</h4>
                    <p>{{ correct.grade }}</p>
                {% else %}
                    <div class="tip">
                        <h3>未评改！</h3>
                        <h3>请等待助教批改作业。</h3>
                    </div>
                {% endif %}
            {% else %}
                {{ render_form(form) }}
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    {{ ckeditor.load() }}
{% endblock %}

devGrasys/templates/student/view_list.html
{% extends 'student/base.html' %}
{% from 'bootstrap/form.html' import render_form %}

{% block title %}查看 - {{ course.name }} 作业 - 学生{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <h3>作业列表：</h3>
            <h4>(标题 - 起始时间 - 截止日期)</h4>
            {% for homework in homework_group %}
                <a class="dead-link"
                   href="{{ url_for('student.view_homework', course_name=course.name,homework_title=homework.title) }}">
                    <span class="oi oi-calendar"></span> {{ homework.title }}
                    - {{ moment(homework.timestamp).format('LL') }}
                    - {{ moment(homework.deadline).format('LL') }}
                </a>
                {% if homework.is_answered(student) %}
                    <span class="oi oi-check"></span>
                {% else %}
                    <span class="oi oi-x"></span>
                {% endif %}
                <br \>
            {% endfor %}
        </div>
    </div>
{% endblock %}